

import React from 'react';
import Link from 'next/link';
import { Shield, Cookie, ArrowLeft } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Cookies Policy | Sitepro.ma',
    description: 'Information about the use of cookies on Sitepro.ma. We protect your privacy in accordance with Moroccan law 09-08.',
    alternates: {
        canonical: 'https://sitepro.ma/en/cookies',
        languages: {
            'fr-MA': 'https://sitepro.ma/cookies',
        },
    },
};

export default function EnCookiesPage() {
    return (
        <div className="min-h-screen bg-gray-50 pt-32 pb-20">
            <div className="container mx-auto px-4 max-w-4xl">
                <Link
                    href="/en"
                    className="inline-flex items-center gap-2 text-primary-600 font-semibold mb-8 hover:gap-3 transition-all"
                >
                    <ArrowLeft size={20} />
                    Back to Home
                </Link>

                <div className="bg-white rounded-[2rem] p-8 md:p-12 shadow-sm border border-gray-100">
                    <div className="flex items-center gap-4 mb-8">
                        <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center text-primary-600">
                            <Cookie size={28} />
                        </div>
                        <h1 className="text-3xl md:text-4xl font-black text-[#022545]">
                            Cookies Policy
                        </h1>
                    </div>

                    <div className="prose prose-blue max-w-none text-gray-600 space-y-6">
                        <p>
                            This policy explains how <strong>Sitepro.ma</strong> uses cookies and similar technologies to recognize you when you visit our website.
                        </p>

                        <section>
                            <h2 className="text-xl font-bold text-[#022545] mb-3">What are cookies?</h2>
                            <p>
                                Cookies are small text files that are stored on your computer or mobile device when you visit a website. They are widely used to make websites work or to work more efficiently, as well as to provide information to the site owners.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-[#022545] mb-3">Why do we use cookies?</h2>
                            <p>
                                We use cookies for several reasons:
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li><strong>Essential Cookies:</strong> Necessary for the technical operation of the site.</li>
                                <li><strong>Performance Cookies:</strong> To analyze how visitors use the site and monitor its performance (via Google Analytics).</li>
                                <li><strong>Functional Cookies:</strong> To remember your preferences (like the chosen language).</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-[#022545] mb-3">Google Analytics</h2>
                            <p>
                                Our site uses Google Analytics, a web analysis service provided by Google. Google Analytics uses cookies to help us analyze how users use the site. The information generated by the cookie about your use of the site will be transmitted to and stored by Google.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-[#022545] mb-3">How to manage cookies?</h2>
                            <p>
                                You can configure your browser to refuse cookies or to warn you when a cookie is sent. Most browsers allow you to:
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>See which cookies you have and delete them individually.</li>
                                <li>Block third-party cookies.</li>
                                <li>Block cookies from specific sites.</li>
                                <li>Block all cookies.</li>
                                <li>Delete all cookies when you close your browser.</li>
                            </ul>
                        </section>

                        <section className="bg-primary-50 p-6 rounded-2xl border border-primary-100 flex gap-4 items-start">
                            <Shield className="text-primary-600 flex-shrink-0" size={24} />
                            <div>
                                <h3 className="font-bold text-[#022545] mb-1">Your privacy is important</h3>
                                <p className="text-sm">
                                    In accordance with Moroccan law 09-08, we are committed to protecting your personal data. For more information, see our <Link href="/en/privacy-policy" className="text-primary-600 underline">Privacy Policy</Link>.
                                </p>
                            </div>
                        </section>

                        <div className="pt-8 border-t border-gray-100 text-sm text-gray-400">
                            Last updated: {new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' })}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
